# Generated by Django 5.1.1 on 2024-12-31 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
